var pipCanvas = new PipCanvas({
    imgList: [
        {
            link: 'img/cover_v1.jpg',
            imgW: '750',
            imgH: '1256',
        },
        {
            link: 'img/p2.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '242',
            areaH: '388',
            areaL: '1127',
            areaT: '431',
        },
        {
            link: 'img/p3.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '137',
            areaH: '219',
            areaL: '243',
            areaT: '474',
        },
        {
            link: 'img/p4.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '88',
            areaH: '142',
            areaL: '1000',
            areaT: '1922',
        },
        {
            link: 'img/p5.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '136',
            areaH: '219',
            areaL: '711',
            areaT: '205',
        },
        {
            link: 'img/p6.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '129',
            areaH: '207',
            areaL: '725',
            areaT: '562',
        },
        {
            link: 'img/p7.jpg',
            imgW: '1875',
            imgH: '3015',
            areaW: '56',
            areaH: '88',
            areaL: '967',
            areaT: '1663',
        }
    ],
    el: '#container',
});
